export enum ERROR_MESSAGE {
  CREATE_ERROR = 'ERROR CREATE PRODUCT!',
  PHOTO_CRETE_ERROR = 'ERROR CREATE PHOTO!',
  UPDATE_ERROR = 'ERROR UPDATE PRODUCT!',
  NOTFOUND_ERROR = 'ERROR PRODUCT NOT FOUND!',
  FAILD_CREATE_ERROR = 'FAILD TO CREATE ENTITY!',
  FAILD_UPDATE_ERROR = 'FAILD TO UPDATE ENTITY!',
  LIST_ERROR = 'LIST NOT FOUND!',
  REMOVE_ERROR = 'PRODUCT NOT REMOVING!',
  GUARD_ERROR = 'PRODUCT NOT FOUND IN REQUEST!',
  PRODUCT_ERROR = 'PRODUCT WITH ID NOT FOUND!',
  PHOTO_ERROR = 'PHOTO WITH ID NOT FOUND!`',
}

// для майбутніх змін (наприклад колір помилки або шрифт)
export type ERROR_TYPE = `${ERROR_MESSAGE}`;
