export enum SUCCESSFULLY_MESSAGE {
  CREATE_SUCCESSFULLY = 'SUCCESSFULLY CREATE PRODUCT!',
  UPDATE_SUCCESSFULLY = 'SUCCESSFULLY UPDATE PRODUCT!',
  NOTFOUND_SUCCESSFULLY = 'SUCCESSFULLY PRODUCT NOT FOUND!',
  FAILD_CREATE_SUCCESSFULLY = 'SUCCESSFULLY FAILD TO CREATE ENTITY!',
  FAILD_UPDATE_SUCCESSFULLY = 'SUCCESSFULLY FAILD TO UPDATE ENTITY!',
  LIST_SUCCESSFULLY = 'SUCCESSFULLY LIST FOUND',
  REMOVE_SUCCESSFULLY = 'SUCCESSFULLY PRODUCT REMOVING',
  GUARD_SUCCESSFULLY = 'SUCCESSFULLY PRODUCT FOUND IN REQUEST',
}

// для майбутніх змін (наприклад колір помилки або шрифт)
export type ERROR_TYPE = `${SUCCESSFULLY_MESSAGE}`;
